on:
  push:
    branches: main

name: rsconnect

jobs:
  rsconnect:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUBPAT }}
      SHINYAPPS_NAME: ${{ secrets.SHINYAPPSNAME }}
      SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPSTOKEN }}
      SHINYAPPS_SECRET: ${{ secrets.SHINYAPPSSECRET }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master

      - name: Query dependencies
        run: |
          install.packages("remotes")
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
        shell: Rscript {0}

      - name: Cache R packages
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: macOS-r-4.0-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: macOS-r-4.0-1-

      - name: Install dependencies
        run: |
          install.packages("remotes")
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Deploy
        run: |
          Rscript rsconnect.R
